<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\mFormFields;
use Illuminate\Support\Facades\DB;
class CDDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $data=[
        [
            'FormFieldName' =>'DateIssued',
            'FormFieldHash' => bcrypt('DateIssued'),
            'InputTypeUID' => '2',
            'FormFieldLabel' => 1,
            'FormFieldLength'=> 100,    
            'FormFieldRequire' => 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],
        [
            'FormFieldName'=>'ClosingDate',
            'FormFieldHash'=>bcrypt('ClosingDate'),
            'InputTypeUID'=> '2',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'DisbursementDate',
            'FormFieldHash'=>bcrypt('DisbursementDate'),
            'InputTypeUID' => '2',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'SettlementAgent',
            'FormFieldHash'=>bcrypt('SettlementAgent'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'File',
            'FormFieldHash'=>bcrypt('File'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'Property',
            'FormFieldHash'=>bcrypt('Property'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'SalePrice',
            'FormFieldHash'=>bcrypt('SalePrice'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'SalePrice',
            'FormFieldHash'=>bcrypt('SalePrice'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'Borrower',
            'FormFieldHash'=>bcrypt('Borrower'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'Seller',
            'FormFieldHash'=>bcrypt('Seller'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [   
            'FormFieldName'=>'Lender',
            'FormFieldHash'=>bcrypt('Lender'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'loanTerm',
            'FormFieldHash'=>bcrypt('loanTerm'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'Purpose',
            'FormFieldHash'=>bcrypt('Purpose'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'Product',
            'FormFieldHash'=>bcrypt('Product'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'LoanType',
            'FormFieldHash'=>bcrypt('LoanType'),
            'InputTypeUID' => '4',
            'FormFieldLabel' => 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'LoadID',
            'FormFieldHash'=>bcrypt('LoadID'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MIC',
            'FormFieldHash'=>bcrypt('MIC'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'LoanAmount',
            'FormFieldHash'=>bcrypt('loanAmount'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'LoanAmountAvaliable',
            'FormFieldHash'=>bcrypt('loanAmount'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'InterestRate',
            'FormFieldHash'=>bcrypt('InterestRate'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'InterestRateAvaliable',
            'FormFieldHash'=>bcrypt('InterestRate'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MonthlyPrincipalInterest',
            'FormFieldHash'=>bcrypt('MonthlyPrincipalInterest'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MonthlyPrincipalInterestAvaliable',
            'FormFieldHash'=>bcrypt('MonthlyPrincipalInterestAvaliable'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PrepaymentPenalty',
            'FormFieldHash'=>bcrypt('PrepaymentPenalty'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PrepaymentPenaltyAvaliable',
            'FormFieldHash'=>bcrypt('PrepaymentPenaltyAvaliable'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'BalloonPaymentAvaliable',
            'FormFieldHash'=>bcrypt('BalloonBalloonPaymentAvaliablePayment'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],
        [
            'FormFieldName'=>'BalloonPayment',
            'FormFieldHash'=>bcrypt('BalloonPayment'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PrincipalInterest',
            'FormFieldHash'=>bcrypt('PrincipalInterest'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PrincipalInterestNextYear',
            'FormFieldHash'=>bcrypt('PrincipalInterestNextYear'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MortgageInsurance',
            'FormFieldHash'=>bcrypt('MortgageInsurance'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MortgageInsuranceNextYear',
            'FormFieldHash'=>bcrypt('MortgageInsuranceNextYear'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'EstimatedEscrow',
            'FormFieldHash'=>bcrypt('EstimatedEscrow'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'EstimatedEscrowNextYear',
            'FormFieldHash'=>bcrypt('EstimatedEscrowNextYear'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'EstlmatodTotalMonthlyPayment',
            'FormFieldHash'=>bcrypt('EstlmatodTotalMonthlyPayment'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'EstlmatodTotalPaymentNextYear',
            'FormFieldHash'=>bcrypt('EstlmatodTotalPaymentNextYear'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'EstimatedTaxesInsuranceAsessments',
            'FormFieldHash'=>bcrypt('EstimatedTaxesInsuranceAsessments'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PropertyTaxesActive',
            'FormFieldHash'=>bcrypt('PropertyTaxesActive'),
            'InputTypeUID'=>'4',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PropertyTaxes',
            'FormFieldHash'=>bcrypt('PropertyTaxes'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'HomeownerInsuranceActive',
            'FormFieldHash'=>bcrypt('HomeownerInsuranceActive'),
            'InputTypeUID'=>'4',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'HomeownerInsurance',
            'FormFieldHash'=>bcrypt('HomeownerInsurance'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'HomeownerAssociationDuesActive',
            'FormFieldHash'=>bcrypt('HomeownerAssociationDues'),
            'InputTypeUID'=>'4',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ],
        [
            'FormFieldName'=>'HomeownerAssociationDues',
            'FormFieldHash'=>bcrypt('HomeownerAssociationDues'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'ClosingCosts ',
            'FormFieldHash'=>bcrypt('ClosingCosts'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'CashtoClose ',
            'FormFieldHash'=>bcrypt('CashtoClose'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 1,
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'data',
            'Active' => 1,
        ], 
    ];
    DB::table('mFormFields')->insert($data);
    }
}
