<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\mFormFields;
use Illuminate\Support\Facades\DB;
class CDDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $data=[
        [
            'FormFieldName' =>'DateIssued',
            'FormFieldHash' => bcrypt('DateIssued'),
            'InputTypeUID' => '2',
            'FormFieldLabel' => 1,
            'FormFieldLength'=> 100,    
            'FormFieldRequire' => 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Closing Information',
            'FormPage'=>1,
            'Active' => 1,
        ],
        [
            'FormFieldName'=>'ClosingDate',
            'FormFieldHash'=>bcrypt('ClosingDate'),
            'InputTypeUID'=> '2',
            'FormFieldLabel'=> "Closing Date",
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Closing Information',
            'FormPage'=>1,
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'DisbursementDate',
            'FormFieldHash'=>bcrypt('DisbursementDate'),
            'InputTypeUID' => '2',
            'FormFieldLabel'=> "Disbursement Date",
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Closing Information',
            'FormPage'=>1,
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'SettlementAgent',
            'FormFieldHash'=>bcrypt('SettlementAgent'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> "Settlement Agent",
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Closing Information',
            'FormPage'=>1,
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'File',
            'FormFieldHash'=>bcrypt('File'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> "File#",
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Closing Information',
            'FormPage'=>1,
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'Property',
            'FormFieldHash'=>bcrypt('Property'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> "Property",
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Closing Information',
            'FormPage'=>1,
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'SalePrice',
            'FormFieldHash'=>bcrypt('SalePrice'),
            'InputTypeUID' => '5',
            'FormFieldLabel'=> "Sale Price",
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Closing Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
          
        [
            'FormFieldName'=>'Borrower',
            'FormFieldHash'=>bcrypt('Borrower'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 'Borrower',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Transaction Information',
            'FormPage'=>1,
            'Active' => 1,
        ],  
         
        [   
            'FormFieldName'=>'Seller',
            'FormFieldHash'=>bcrypt('Seller'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 'Seller',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Transaction Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
         
        [   
            'FormFieldName'=>'Lender',
            'FormFieldHash'=>bcrypt('Lender'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 'Lender',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Transaction Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'LoanTerm',
            'FormFieldHash'=>bcrypt('loanTerm'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 'Loan Term',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'Purpose',
            'FormFieldHash'=>bcrypt('Purpose'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 'Purpose',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'Product',
            'FormFieldHash'=>bcrypt('Product'),
            'InputTypeUID' => '1',
            'FormFieldLabel'=> 'Product',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'LoanType',
            'FormFieldHash'=>bcrypt('LoanType'),
            'InputTypeUID' => '4',
            'FormFieldLabel' => 'Loan Type',
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'LoanID',
            'FormFieldHash'=>bcrypt('LoanID'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 'Loan ID#',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Information',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MIC',
            'FormFieldHash'=>bcrypt('MIC'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 'MIC#',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Information',
            'FormPage'=>1,
            'Active' => 1,
        ],  
        [
            'FormFieldName'=>'LoanAmount',
            'FormFieldHash'=>bcrypt('loanAmount'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 'Loan Amount',
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'LoanAmountAvaliable',
            'FormFieldHash'=>bcrypt('LoanAmountAvaliable'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 'Loan Amount',
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'InterestRate',
            'FormFieldHash'=>bcrypt('InterestRate'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 'Interest Rate',
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'InterestRateAvaliable',
            'FormFieldHash'=>bcrypt('InterestRateAvaliable'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 'Interest Rate',
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MonthlyPrincipalInterest',
            'FormFieldHash'=>bcrypt('MonthlyPrincipalInterest'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 'Monthly Principal & Interest <br/> See Projected Payments below for your Estimated Total Monthly Payment',
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'MonthlyPrincipalInterestAvaliable',
            'FormFieldHash'=>bcrypt('MonthlyPrincipalInterestAvaliable'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 'Monthly Principal & Interest <br/> See Projected Payments below for your Estimated Total Monthly Payment',
            'FormFieldLength'=> 50,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PrepaymentPenalty',
            'FormFieldHash'=>bcrypt('PrepaymentPenalty'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 'Prepayment Penalty',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'PrepaymentPenaltyAvaliable',
            'FormFieldHash'=>bcrypt('PrepaymentPenaltyAvaliable'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 'Prepayment Penalty',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
        [
            'FormFieldName'=>'BalloonPaymentAvaliable',
            'FormFieldHash'=>bcrypt('BalloonBalloonPaymentAvaliablePayment'),
            'InputTypeUID'=>'1',
            'FormFieldLabel'=> 'Balloon Payment',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ],
        [
            'FormFieldName'=>'BalloonPayment',
            'FormFieldHash'=>bcrypt('BalloonPayment'),
            'InputTypeUID'=>'3',
            'FormFieldLabel'=> 'Balloon Payment',
            'FormFieldLength'=> 100,
            'FormFieldRequire'=> 1,
            'FormFieldPosition' => '1',
            'FormFieldInstruction' => 'General',
            'FormFieldPlaceholder'=>'value',
            'FormGrouping'=>'Loan Terms',
            'FormPage'=>1,
            'Active' => 1,
        ], 
            ];
    DB::table('mFormFields')->insert($data);
    }
}
