<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\mTemplateFields;
use Illuminate\Support\Facades\DB;
class CDDetailsTempSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $FFUID=1;
        $data=[
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'DateIssued',
            'TempFieldHash' => bcrypt('DateIssued'),
            'InputTypeUID' => '2',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'ClosingDate',
            'TempFieldHash'=>bcrypt('ClosingDate'),
            'InputTypeUID'=> '2',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'DisbursementDate',
            'TempFieldHash'=>bcrypt('DisbursementDate'),
            'InputTypeUID' => '2',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'SettlementAgent',
            'TempFieldHash'=>bcrypt('SettlementAgent'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'File',
            'TempFieldHash'=>bcrypt('File'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'Property',
            'TempFieldHash'=>bcrypt('Property'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'SalePrice',
            'TempFieldHash'=>bcrypt('SalePrice'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
          
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'Borrower',
            'TempFieldHash'=>bcrypt('Borrower'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],  
         
        [   
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'Lender',
            'TempFieldHash'=>bcrypt('Lender'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'LoanTerm',
            'TempFieldHash'=>bcrypt('loanTerm'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'Purpose',
            'TempFieldHash'=>bcrypt('Purpose'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'Product',
            'TempFieldHash'=>bcrypt('Product'),
            'InputTypeUID' => '1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'LoanType',
            'TempFieldHash'=>bcrypt('LoanType'),
            'InputTypeUID' => '4',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 50,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'LoanID',
            'TempFieldHash'=>bcrypt('LoanID'),
            'InputTypeUID'=>'1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'MIC',
            'TempFieldHash'=>bcrypt('MIC'),
            'InputTypeUID'=>'1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],  
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'LoanAmount',
            'TempFieldHash'=>bcrypt('loanAmount'),
            'InputTypeUID'=>'1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 50,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'LoanAmountAvaliable',
            'TempFieldHash'=>bcrypt('LoanAmountAvaliable'),
            'InputTypeUID'=>'3',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 50,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'InterestRate',
            'TempFieldHash'=>bcrypt('InterestRate'),
            'InputTypeUID'=>'1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 50,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'InterestRateAvaliable',
            'TempFieldHash'=>bcrypt('InterestRateAvaliable'),
            'InputTypeUID'=>'3',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 50,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'MonthlyPrincipalInterest',
            'TempFieldHash'=>bcrypt('MonthlyPrincipalInterest'),
            'InputTypeUID'=>'1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 50,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'MonthlyPrincipalInterestAvaliable',
            'TempFieldHash'=>bcrypt('MonthlyPrincipalInterestAvaliable'),
            'InputTypeUID'=>'3',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 50,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'PrepaymentPenalty',
            'TempFieldHash'=>bcrypt('PrepaymentPenalty'),
            'InputTypeUID'=>'1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'PrepaymentPenaltyAvaliable',
            'TempFieldHash'=>bcrypt('PrepaymentPenaltyAvaliable'),
            'InputTypeUID'=>'3',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'BalloonPaymentAvaliable',
            'TempFieldHash'=>bcrypt('BalloonBalloonPaymentAvaliablePayment'),
            'InputTypeUID'=>'1',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName'=>'BalloonPayment',
            'TempFieldHash'=>bcrypt('BalloonPayment'),
            'InputTypeUID'=>'3',
            'TempFieldLabel'=> 1,
            'TempFieldLength'=> 100,
            'TempFieldRequire'=> 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'data',
            'Active' => 1,
        ], 
            ];
    DB::table('mTemplateFields')->insert($data);
    }
}
