<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\mTemplateFields;
use Illuminate\Support\Facades\DB;

class CDfifthpageTempSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $FFUID=859;
        $data=[
        //
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'TotalofPayments',
            'TempFieldHash' => bcrypt('TotalofPayments'),
            'InputTypeUID' => '5',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'FinanceCharge',
            'TempFieldHash' => bcrypt('FinanceCharge'),
            'InputTypeUID' => '5',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'AmountFinanced',
            'TempFieldHash' => bcrypt('AmountFinanced'),
            'InputTypeUID' => '5',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'AnnualPercentageRate',
            'TempFieldHash' => bcrypt('AnnualPercentageRate'),
            'InputTypeUID' => '5',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'TotalInterestPercentage',
            'TempFieldHash' => bcrypt('TotalInterestPercentage'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LiabilityafterForeclosure',
            'TempFieldHash' => bcrypt('LiabilityafterForeclosure'),
            'InputTypeUID' => '4',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LiabilityafterForeclosureSecond',
            'TempFieldHash' => bcrypt('LiabilityafterForeclosureSecond'),
            'InputTypeUID' => '4',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderName',
            'TempFieldHash' => bcrypt('LenderName'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderName',
            'TempFieldHash' => bcrypt('LenderName'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerName',
            'TempFieldHash' => bcrypt('MortgageBrokerName'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerName',
            'TempFieldHash' => bcrypt('RealEstateBrokerName'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerNameTwo',
            'TempFieldHash' => bcrypt('RealEstateBrokerNameTwo'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentName',
            'TempFieldHash' => bcrypt('SettlementAgentName'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderAddress',
            'TempFieldHash' => bcrypt('LenderAddress'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerAddress',
            'TempFieldHash' => bcrypt('MortgageBrokerAddress'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=> '2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerAddress',
            'TempFieldHash' => bcrypt('RealEstateBrokerAddress'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementBrokerAddress',
            'TempFieldHash' => bcrypt('SettlementBrokerAddress'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderNMLSID ',
            'TempFieldHash' => bcrypt('LenderNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerNMLSID',
            'TempFieldHash' => bcrypt('MortgageBrokerNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerNMLSID',
            'TempFieldHash' => bcrypt('RealEstateBrokerNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSecondNMLSID',
            'TempFieldHash' => bcrypt('RealEstateBrokerSecondNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentNMLSID',
            'TempFieldHash' => bcrypt('SettlementAgentNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderSTLicenseID',
            'TempFieldHash' => bcrypt('LenderSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerSTLicenseID',
            'TempFieldHash' => bcrypt('MortgageBrokerSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSTLicenseID',
            'TempFieldHash' => bcrypt('RealEstateBrokerSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSecondSTLicenseID',
            'TempFieldHash' => bcrypt('RealEstateBrokerSecondSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentSTLicenseID',
            'TempFieldHash' => bcrypt('SettlementAgentSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderContact',
            'TempFieldHash' => bcrypt('LenderContact'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerContact',
            'TempFieldHash' => bcrypt('MortgageBrokerContact'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerContact',
            'TempFieldHash' => bcrypt('RealEstateBrokerContact'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSecondContact',
            'TempFieldHash' => bcrypt('RealEstateBrokerSecondContact'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentContact',
            'TempFieldHash' => bcrypt('SettlementAgentContact'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderContactNMLSID',
            'TempFieldHash' => bcrypt('LenderContactNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerContactNMLSID',
            'TempFieldHash' => bcrypt('MortgageBrokerContactNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerContactNMLSID',
            'TempFieldHash' => bcrypt('RealEstateBrokerContactNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSecondContactNMLSID',
            'TempFieldHash' => bcrypt('RealEstateBrokerSecondContactNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentContactNMLSID',
            'TempFieldHash' => bcrypt('SettlementAgentContactNMLSID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderContactSTLicenseID',
            'TempFieldHash' => bcrypt('LenderContactSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerContactSTLicenseID',
            'TempFieldHash' => bcrypt('MortgageBrokerContactSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerContactSTLicenseID',
            'TempFieldHash' => bcrypt('RealEstateBrokerContactSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSecondContactSTLicenseID',
            'TempFieldHash' => bcrypt('RealEstateBrokerSecondContactSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentContactSTLicenseID',
            'TempFieldHash' => bcrypt('SettlementAgentContactSTLicenseID'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderEmail',
            'TempFieldHash' => bcrypt('LenderEmail'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerEmail',
            'TempFieldHash' => bcrypt('MortgageBrokerEmail'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerEmail',
            'TempFieldHash' => bcrypt('RealEstateBrokerEmail'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSecondEmail',
            'TempFieldHash' => bcrypt('RealEstateBrokerSecondEmail'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentEmail',
            'TempFieldHash' => bcrypt('SettlementAgentEmail'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'LenderPhone',
            'TempFieldHash' => bcrypt('LenderPhone'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'MortgageBrokerPhone',
            'TempFieldHash' => bcrypt('MortgageBrokerPhone'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerPhone',
            'TempFieldHash' => bcrypt('RealEstateBrokerPhone'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'RealEstateBrokerSecondPhone',
            'TempFieldHash' => bcrypt('RealEstateBrokerSecondPhone'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
        [
            'FormFieldUID' => ++$FFUID,
            'TemplateUID' => 1,
            'TempFieldName' =>'SettlementAgentPhone',
            'TempFieldHash' => bcrypt('SettlementAgentPhone'),
            'InputTypeUID' => '1',
            'TempFieldLabel' => 1,
            'TempFieldLength'=> 100,    
            'TempFieldRequire' => 1,
            'TempFieldPosition' => '1',
            'TempFieldInstruction' => 'General',
            'TempFieldPlaceholder'=>'value',
            'TempGrouping'=>'2',
            'Active' => 1,
        ],
    ];
    DB::table('mTemplateFields')->insert($data);
    }
}
