<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\mTemplateFields;
use Illuminate\Support\Facades\DB;
class CDfourthpageTempSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $FFUID=236;
        $data=[
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'Assumption',
                'TempFieldHash' => bcrypt('Assumption'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'AssumptionAvaliable',
                'TempFieldHash' => bcrypt('AssumptionAvaliable'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DemandFeature',
                'TempFieldHash' => bcrypt('DemandFeature'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DemandFeatureAvaliable',
                'TempFieldHash' => bcrypt('DemandFeatureAvaliable'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'NegativeAmortization',
                'TempFieldHash' => bcrypt('NegativeAmortization'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'NegativeAmortizationSecond',
                'TempFieldHash' => bcrypt('NegativeAmortizationSecond'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'NegativeAmortizationThird',
                'TempFieldHash' => bcrypt('NegativeAmortizationThird'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'PartialPayments',
                'TempFieldHash' => bcrypt('PartialPayments'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'PartialPaymentsSecond',
                'TempFieldHash' => bcrypt('PartialPaymentsSecond'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'PartialPaymentsThird',
                'TempFieldHash' => bcrypt('PartialPaymentsThird'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'EscrowAccount',
                'TempFieldHash' => bcrypt('EscrowAccount'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'EscrowedPropertyCostsoverYear1',
                'TempFieldHash' => bcrypt('EscrowedPropertyCostsoverYear1'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'NonEscrowedPropertyCostsoverYear1',
                'TempFieldHash' => bcrypt('NonEscrowedPropertyCostsoverYear1'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'InitialEscrowPayment',
                'TempFieldHash' => bcrypt('InitialEscrowPayment'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'MonthlyEscrowPayment',
                'TempFieldHash' => bcrypt('MonthlyEscrowPayment'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'EscrowActive',
                'TempFieldHash' => bcrypt('EscrowActive'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'EscrowActiveTwo',
                'TempFieldHash' => bcrypt('EscrowActiveTwo'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'EscrowActiveThree',
                'TempFieldHash' => bcrypt('EscrowActiveThree'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'NoEscrowOne',
                'TempFieldHash' => bcrypt('NoEscrowOne'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'EscrowWaiverFee',
                'TempFieldHash' => bcrypt('EscrowWaiverFee'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
        ];
        DB::table('mTemplateFields')->insert($data);
    }
}
