<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\mTemplateFields;
use Illuminate\Support\Facades\DB;
class CDthirdpageTempSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $FFUID=308;
        $data=[
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'TotalClosingCostsLoanEstimate',
                'TempFieldHash' => bcrypt('TotalClosingCostsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'TotalClosingCostsFinal',
                'TempFieldHash' => bcrypt('TotalClosingCostsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'TotalClosingCostsDidChange',
                'TempFieldHash' => bcrypt('TotalClosingCostsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsPaidLoanEstimate',
                'TempFieldHash' => bcrypt('ClosingCostsPaidLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsPaidFinal',
                'TempFieldHash' => bcrypt('ClosingCostsPaidFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsPaidDidChange',
                'TempFieldHash' => bcrypt('ClosingCostsPaidDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsFinancedLoanEstimate',
                'TempFieldHash' => bcrypt('ClosingCostsFinancedLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsFinancedFinal',
                'TempFieldHash' => bcrypt('ClosingCostsFinancedFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsFinancedDidChange',
                'TempFieldHash' => bcrypt('ClosingCostsFinanced'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DownPaymentLoanEstimate',
                'TempFieldHash' => bcrypt('DownPaymentLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DownPaymentFinal',
                'TempFieldHash' => bcrypt('DownPaymentFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DownPaymentDidChange',
                'TempFieldHash' => bcrypt('ClosingCostsFinanced'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DepositLoanEstimate',
                'TempFieldHash' => bcrypt('DepositLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DepositFinal',
                'TempFieldHash' => bcrypt('DepositFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DepositDidChange',
                'TempFieldHash' => bcrypt('DepositDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'FundsLoanEstimate',
                'TempFieldHash' => bcrypt('FundsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'FundsFinal',
                'TempFieldHash' => bcrypt('FundsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'FundsDidChange',
                'TempFieldHash' => bcrypt('FundsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsLoanEstimate',
                'TempFieldHash' => bcrypt('SellerCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsFinal',
                'TempFieldHash' => bcrypt('SellerCreditsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsDidChange',
                'TempFieldHash' => bcrypt('SellerCreditsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsLoanEstimate',
                'TempFieldHash' => bcrypt('SellerCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsFinal',
                'TempFieldHash' => bcrypt('SellerCreditsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsDidChange',
                'TempFieldHash' => bcrypt('SellerCreditsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsLoanEstimate',
                'TempFieldHash' => bcrypt('AdjustmentAndOtherCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'AdjustmentAndOtherCreditsFinal',
                'TempFieldHash' => bcrypt('AdjustmentAndOtherCreditsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'AdjustmentAndOtherCreditsDidChange',
                'TempFieldHash' => bcrypt('AdjustmentAndOtherCreditsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerClosingDue',
                'TempFieldHash' => bcrypt('BorrowerClosingDue'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerClosingDue',
                'TempFieldHash' => bcrypt('SellerClosingDue'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerSalePrice',
                'TempFieldHash' => bcrypt('BorrowerSalePrice'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerSalePrice',
                'TempFieldHash' => bcrypt('SellerSalePrice'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'PersonalPropertySale',
                'TempFieldHash' => bcrypt('PersonalPropertySale'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'General',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
             
        ];
        DB::table('mTemplateFields')->insert($data);
    }
}
