<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CDthirdpage extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data=[
            [
                'FormFieldName' =>'TotalClosingCostsLoanEstimate',
                'FormFieldHash' => bcrypt('TotalClosingCostsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'TotalClosingCostsFinal',
                'FormFieldHash' => bcrypt('TotalClosingCostsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'TotalClosingCostsDidChange',
                'FormFieldHash' => bcrypt('TotalClosingCostsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidLoanEstimate',
                'FormFieldHash' => bcrypt('ClosingCostsPaidLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidFinal',
                'FormFieldHash' => bcrypt('ClosingCostsPaidFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsPaidDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedLoanEstimate',
                'FormFieldHash' => bcrypt('ClosingCostsFinancedLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedFinal',
                'FormFieldHash' => bcrypt('ClosingCostsFinancedFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsFinanced'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentLoanEstimate',
                'FormFieldHash' => bcrypt('DownPaymentLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentFinal',
                'FormFieldHash' => bcrypt('DownPaymentFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsFinanced'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositLoanEstimate',
                'FormFieldHash' => bcrypt('DepositLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositFinal',
                'FormFieldHash' => bcrypt('DepositFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositDidChange',
                'FormFieldHash' => bcrypt('DepositDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsLoanEstimate',
                'FormFieldHash' => bcrypt('FundsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsFinal',
                'FormFieldHash' => bcrypt('FundsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsDidChange',
                'FormFieldHash' => bcrypt('FundsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsLoanEstimate',
                'FormFieldHash' => bcrypt('SellerCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsFinal',
                'FormFieldHash' => bcrypt('SellerCreditsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsDidChange',
                'FormFieldHash' => bcrypt('SellerCreditsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsLoanEstimate',
                'FormFieldHash' => bcrypt('SellerCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsFinal',
                'FormFieldHash' => bcrypt('SellerCreditsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsDidChange',
                'FormFieldHash' => bcrypt('SellerCreditsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsLoanEstimate',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsFinal',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsDidChange',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerClosingDue',
                'FormFieldHash' => bcrypt('BorrowerClosingDue'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerClosingDue',
                'FormFieldHash' => bcrypt('SellerClosingDue'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerSalePrice',
                'FormFieldHash' => bcrypt('BorrowerSalePrice'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerSalePrice',
                'FormFieldHash' => bcrypt('SellerSalePrice'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'PersonalPropertySale',
                'FormFieldHash' => bcrypt('PersonalPropertySale'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
             
        ];
    }
}
