<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\mTemplateFields;
use Illuminate\Support\Facades\DB;
class CDthirdpageTempSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $FFUID=717;
        $data=[
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'TotalClosingCostsLoanEstimate',
                'TempFieldHash' => bcrypt('TotalClosingCostsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'TotalClosingCosts,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'TotalClosingCostsFinal',
                'TempFieldHash' => bcrypt('TotalClosingCostsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'TotalClosingCosts,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'TotalClosingCostsDidChange',
                'TempFieldHash' => bcrypt('TotalClosingCostsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'TotalClosingCosts,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsPaidLoanEstimate',
                'TempFieldHash' => bcrypt('ClosingCostsPaidLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'ClosingCostsPaid,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsPaidFinal',
                'TempFieldHash' => bcrypt('ClosingCostsPaidFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'ClosingCosts,PaidFinal',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsPaidDidChange',
                'TempFieldHash' => bcrypt('ClosingCostsPaidDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'ClosingCostsPaid,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsFinancedLoanEstimate',
                'TempFieldHash' => bcrypt('ClosingCostsFinancedLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'ClosingCostsFinanced,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsFinancedFinal',
                'TempFieldHash' => bcrypt('ClosingCostsFinancedFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'ClosingCostsFinanced,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsFinancedDidChange',
                'TempFieldHash' => bcrypt('ClosingCostsFinancedDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'ClosingCostsFinanced,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DownPaymentLoanEstimate',
                'TempFieldHash' => bcrypt('DownPaymentLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'DownPayment,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DownPaymentFinal',
                'TempFieldHash' => bcrypt('DownPaymentFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'DownPayment,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DownPaymentDidChange',
                'TempFieldHash' => bcrypt('DownPaymentDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'DownPayment,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DepositLoanEstimate',
                'TempFieldHash' => bcrypt('DepositLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'Deposit,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DepositFinal',
                'TempFieldHash' => bcrypt('DepositFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'Deposit,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DepositDidChange',
                'TempFieldHash' => bcrypt('DepositDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'Deposit,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'FundsLoanEstimate',
                'TempFieldHash' => bcrypt('FundsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'Funds,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'FundsFinal',
                'TempFieldHash' => bcrypt('FundsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'Funds,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'FundsDidChange',
                'TempFieldHash' => bcrypt('FundsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'Funds,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsLoanEstimate',
                'TempFieldHash' => bcrypt('SellerCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerCredits,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsFinal',
                'TempFieldHash' => bcrypt('SellerCreditsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerCredits,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsDidChange',
                'TempFieldHash' => bcrypt('SellerCreditsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerCredits,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'AdjustmentAndOtherCreditsLoanEstimate',
                'TempFieldHash' => bcrypt('AdjustmentAndOtherCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'AdjustmentAndOtherCredits,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'AdjustmentAndOtherCreditsFinal',
                'TempFieldHash' => bcrypt('AdjustmentAndOtherCreditsFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'AdjustmentAndOtherCredits,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'AdjustmentAndOtherCreditsDidChange',
                'TempFieldHash' => bcrypt('AdjustmentAndOtherCreditsDidChange'),
                'InputTypeUID' => '3',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'AdjustmentAndOtherCredits,DidChange',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'CashToCloseLoanEstimate',
                'TempFieldHash' => bcrypt('CashToCloseLoanEstimate'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CashToClose,LoanEstimate',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'CashToCloseFinal',
                'TempFieldHash' => bcrypt('CashToCloseFinal'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CashToClose,Final',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerClosingDue',
                'TempFieldHash' => bcrypt('BorrowerClosingDue'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerClosingDue',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerClosingDue',
                'TempFieldHash' => bcrypt('SellerClosingDue'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerClosingDue',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerSalePrice',
                'TempFieldHash' => bcrypt('BorrowerSalePrice'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerSalePrice',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerSalePrice',
                'TempFieldHash' => bcrypt('SellerSalePrice'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerSalePrice',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SalePriceBorrowerProperty',
                'TempFieldHash' => bcrypt('SalePriceBorrowerProperty'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SalePriceBorrowerProperty',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SalePriceSellerProperty',
                'TempFieldHash' => bcrypt('SalePriceSellerProperty'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SalePriceSellerProperty',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ClosingCostsPaidAtClosing',
                'TempFieldHash' => bcrypt('ClosingCostsPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'ClosingCostsPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerAdjustments1',
                'TempFieldHash' => bcrypt('BorrowerAdjustments1'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustments1',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerAdjustments2',
                'TempFieldHash' => bcrypt('BorrowerAdjustments2'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustments2',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCityTownTaxes',
                'TempFieldHash' => bcrypt('SellerCityTownTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerAdjustmentsPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCountyTaxes',
                'TempFieldHash' => bcrypt('SellerCountyTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerAdjustmentsPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerAssessments',
                'TempFieldHash' => bcrypt('SellerAssessments'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerAdjustmentsPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerCityTownTaxes',
                'TempFieldHash' => bcrypt('BorrowerCityTownTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustmentsPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerCountyTaxes',
                'TempFieldHash' => bcrypt('BorrowerCountyTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustmentsPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerAssessments',
                'TempFieldHash' => bcrypt('BorrowerAssessments'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustmentsPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerHOADues',
                'TempFieldHash' => bcrypt('SellerHOADues'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerHOADues',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerHOADues',
                'TempFieldHash' => bcrypt('BorrowerHOADues'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerHOADues',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('BorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerDueAtClosing',
                'TempFieldHash' => bcrypt('SellerDueAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerDueAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'DepositBorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('DepositBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'DepositBorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'LoanAmountBorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('LoanAmountBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'LoanAmountBorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'LoanAssumedBorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('LoanAssumedBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'LoanAssumedBorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCreditsBorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('SellerCreditsBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerCreditsBorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'RebateBorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('RebateBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'RebateBorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'AdjustmentsNBorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('AdjustmentsNBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'Adjustments-N-BorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerCityTownTaxes',
                'TempFieldHash' => bcrypt('BorrowerCityTownTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustmentsUnPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerCountyTaxes',
                'TempFieldHash' => bcrypt('BorrowerCountyTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustmentsUnPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerAssessments',
                'TempFieldHash' => bcrypt('BorrowerAssessments'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'BorrowerAdjustmentsUnPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'ExcessDepositDues',
                'TempFieldHash' => bcrypt('ExcessDepositDues'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerDueAtClosingExcessDepositDues',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'PaidClosingCosts',
                'TempFieldHash' => bcrypt('PaidClosingCosts'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerDueAtClosingPaidClosingCosts',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'LoanAssumed',
                'TempFieldHash' => bcrypt('LoanAssumed'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerDueAtClosingLoanAssumed',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'FirstLoanPayoff',
                'TempFieldHash' => bcrypt('FirstLoanPayoff'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerDueAtClosingFirstLoanPayoff',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SecondLoanPayoff',
                'TempFieldHash' => bcrypt('SecondLoanPayoff'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerDueAtClosingSecondLoanPayoff',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCredit',
                'TempFieldHash' => bcrypt('SellerCredit'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerDueAtClosingSellerCredit',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCityTownTaxes',
                'TempFieldHash' => bcrypt('SellerCityTownTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerAdjustmentsUnPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCountyTaxes',
                'TempFieldHash' => bcrypt('SellerCountyTaxes'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerAdjustmentsUnPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerAssessments',
                'TempFieldHash' => bcrypt('SellerAssessments'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'SellerAdjustmentsUnPaidBySeller',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerDueAtClosing',
                'TempFieldHash' => bcrypt('BorrowerDueAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationBorrowerDueAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerPaidAtClosing',
                'TempFieldHash' => bcrypt('BorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationBorrowerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerCashToCloseFrom',
                'TempFieldHash' => bcrypt('BorrowerCashToFrom'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationBorrowerCashToCloseFrom',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'BorrowerCashToCloseTo',
                'TempFieldHash' => bcrypt('BorrowerCashToTo'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationBorrowerCashToCloseTo',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerDueAtClosing',
                'TempFieldHash' => bcrypt('SellerDueAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationSellerDueAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerPaidAtClosing',
                'TempFieldHash' => bcrypt('SellerPaidAtClosing'),
                'InputTypeUID' => '5',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationSellerPaidAtClosing',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCashToCloseFrom',
                'TempFieldHash' => bcrypt('SellerCashToFrom'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationSellerCashToCloseFrom',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldUID' => ++$FFUID,
                'TemplateUID' => 1,
                'TempFieldName' =>'SellerCashToCloseTo',
                'TempFieldHash' => bcrypt('SellerCashToTo'),
                'InputTypeUID' => '4',
                'TempFieldLabel' => 1,
                'TempFieldLength'=> 100,    
                'TempFieldRequire' => 1,
                'TempFieldPosition' => '1',
                'TempFieldInstruction' => 'CalculationSellerCashToCloseTo',
                'TempFieldPlaceholder'=>'value',
                'TempGrouping'=>'2',
                'Active' => 1,
            ],
        ];
        DB::table('mTemplateFields')->insert($data);
    }
}
