<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\mFormFields;
use Illuminate\Support\Facades\DB;
class CDthirdpageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data=[
            [
                'FormFieldName' =>'TotalClosingCostsLoanEstimate',
                'FormFieldHash' => bcrypt('TotalClosingCostsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'TotalClosingCosts,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'TotalClosingCostsFinal',
                'FormFieldHash' => bcrypt('TotalClosingCostsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'TotalClosingCosts,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'TotalClosingCostsDidChange',
                'FormFieldHash' => bcrypt('TotalClosingCostsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'TotalClosingCosts,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidLoanEstimate',
                'FormFieldHash' => bcrypt('ClosingCostsPaidLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsPaid,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidFinal',
                'FormFieldHash' => bcrypt('ClosingCostsPaidFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCosts,PaidFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsPaidDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsPaid,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedLoanEstimate',
                'FormFieldHash' => bcrypt('ClosingCostsFinancedLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsFinanced,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedFinal',
                'FormFieldHash' => bcrypt('ClosingCostsFinancedFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsFinanced,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsFinancedDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsFinanced,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentLoanEstimate',
                'FormFieldHash' => bcrypt('DownPaymentLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DownPayment,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentFinal',
                'FormFieldHash' => bcrypt('DownPaymentFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DownPayment,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentDidChange',
                'FormFieldHash' => bcrypt('DownPaymentDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DownPayment,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositLoanEstimate',
                'FormFieldHash' => bcrypt('DepositLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Deposit,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositFinal',
                'FormFieldHash' => bcrypt('DepositFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Deposit,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositDidChange',
                'FormFieldHash' => bcrypt('DepositDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Deposit,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsLoanEstimate',
                'FormFieldHash' => bcrypt('FundsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Funds,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsFinal',
                'FormFieldHash' => bcrypt('FundsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Funds,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsDidChange',
                'FormFieldHash' => bcrypt('FundsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Funds,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsLoanEstimate',
                'FormFieldHash' => bcrypt('SellerCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerCredits,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsFinal',
                'FormFieldHash' => bcrypt('SellerCreditsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerCredits,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsDidChange',
                'FormFieldHash' => bcrypt('SellerCreditsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerCredits,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsLoanEstimate',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'AdjustmentAndOtherCredits,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsFinal',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'AdjustmentAndOtherCredits,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsDidChange',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'AdjustmentAndOtherCredits,DidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'CashToCloseLoanEstimate',
                'FormFieldHash' => bcrypt('CashToCloseLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CashToClose,LoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'CashToCloseFinal',
                'FormFieldHash' => bcrypt('CashToCloseFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CashToClose,Final',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            
            [
                'FormFieldName' =>'BorrowerClosingDue',
                'FormFieldHash' => bcrypt('BorrowerClosingDue'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerClosingDue',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerClosingDue',
                'FormFieldHash' => bcrypt('SellerClosingDue'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerClosingDue',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerSalePrice',
                'FormFieldHash' => bcrypt('BorrowerSalePrice'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerSalePrice',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerSalePrice',
                'FormFieldHash' => bcrypt('SellerSalePrice'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerSalePrice',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SalePriceBorrowerProperty',
                'FormFieldHash' => bcrypt('SalePriceBorrowerProperty'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SalePriceBorrowerProperty',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SalePriceSellerProperty',
                'FormFieldHash' => bcrypt('SalePriceSellerProperty'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SalePriceSellerProperty',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidAtClosing',
                'FormFieldHash' => bcrypt('ClosingCostsPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerAdjustments1',
                'FormFieldHash' => bcrypt('BorrowerAdjustments1'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustments1',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerAdjustments2',
                'FormFieldHash' => bcrypt('BorrowerAdjustments2'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustments2',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCityTownTaxes',
                'FormFieldHash' => bcrypt('SellerCityTownTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerAdjustmentsPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCountyTaxes',
                'FormFieldHash' => bcrypt('SellerCountyTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerAdjustmentsPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerAssessments',
                'FormFieldHash' => bcrypt('SellerAssessments'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerAdjustmentsPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerCityTownTaxes',
                'FormFieldHash' => bcrypt('BorrowerCityTownTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustmentsPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerCountyTaxes',
                'FormFieldHash' => bcrypt('BorrowerCountyTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustmentsPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerAssessments',
                'FormFieldHash' => bcrypt('BorrowerAssessments'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustmentsPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerHOADues',
                'FormFieldHash' => bcrypt('SellerHOADues'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerHOADues',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerHOADues',
                'FormFieldHash' => bcrypt('BorrowerHOADues'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerHOADues',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('BorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerDueAtClosing',
                'FormFieldHash' => bcrypt('SellerDueAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerDueAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositBorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('DepositBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DepositBorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'LoanAmountBorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('LoanAmountBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'LoanAmountBorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'LoanAssumedBorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('LoanAssumedBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'LoanAssumedBorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsBorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('SellerCreditsBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerCreditsBorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'RebateBorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('RebateBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'RebateBorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentsNBorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('AdjustmentsNBorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Adjustments-N-BorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerCityTownTaxes',
                'FormFieldHash' => bcrypt('BorrowerCityTownTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustmentsUnPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerCountyTaxes',
                'FormFieldHash' => bcrypt('BorrowerCountyTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustmentsUnPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerAssessments',
                'FormFieldHash' => bcrypt('BorrowerAssessments'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerAdjustmentsUnPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ExcessDepositDues',
                'FormFieldHash' => bcrypt('ExcessDepositDues'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerDueAtClosingExcessDepositDues',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'PaidClosingCosts',
                'FormFieldHash' => bcrypt('PaidClosingCosts'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerDueAtClosingPaidClosingCosts',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'LoanAssumed',
                'FormFieldHash' => bcrypt('LoanAssumed'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerDueAtClosingLoanAssumed',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FirstLoanPayoff',
                'FormFieldHash' => bcrypt('FirstLoanPayoff'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerDueAtClosingFirstLoanPayoff',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SecondLoanPayoff',
                'FormFieldHash' => bcrypt('SecondLoanPayoff'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerDueAtClosingSecondLoanPayoff',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCredit',
                'FormFieldHash' => bcrypt('SellerCredit'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerDueAtClosingSellerCredit',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCityTownTaxes',
                'FormFieldHash' => bcrypt('SellerCityTownTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerAdjustmentsUnPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCountyTaxes',
                'FormFieldHash' => bcrypt('SellerCountyTaxes'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerAdjustmentsUnPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerAssessments',
                'FormFieldHash' => bcrypt('SellerAssessments'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerAdjustmentsUnPaidBySeller',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerDueAtClosing',
                'FormFieldHash' => bcrypt('BorrowerDueAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationBorrowerDueAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerPaidAtClosing',
                'FormFieldHash' => bcrypt('BorrowerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationBorrowerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerCashToCloseFrom',
                'FormFieldHash' => bcrypt('BorrowerCashToFrom'),
                'InputTypeUID' => '4',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationBorrowerCashToCloseFrom',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerCashToCloseTo',
                'FormFieldHash' => bcrypt('BorrowerCashToTo'),
                'InputTypeUID' => '4',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationBorrowerCashToCloseTo',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerDueAtClosing',
                'FormFieldHash' => bcrypt('SellerDueAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationSellerDueAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerPaidAtClosing',
                'FormFieldHash' => bcrypt('SellerPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationSellerPaidAtClosing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCashToCloseFrom',
                'FormFieldHash' => bcrypt('SellerCashToFrom'),
                'InputTypeUID' => '4',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationSellerCashToCloseFrom',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCashToCloseTo',
                'FormFieldHash' => bcrypt('SellerCashToTo'),
                'InputTypeUID' => '4',
                'FormFieldLabel' => 1,
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CalculationSellerCashToCloseTo',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'2',
                'Active' => 1,
            ],
        ];
        DB::table('mFormFields')->insert($data);
    }
}
