<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\mFormFields;
use Illuminate\Support\Facades\DB;
class CDthirdpage extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data=[
            [
                'FormFieldName' =>'TotalClosingCostsLoanEstimate',
                'FormFieldHash' => bcrypt('TotalClosingCostsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Total Closing Costs(J)',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'TotalClosingCostsLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'TotalClosingCostsFinal',
                'FormFieldHash' => bcrypt('TotalClosingCostsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Total Closing Costs(J)',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'TotalClosingCostsFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'TotalClosingCostsDidChange',
                'FormFieldHash' => bcrypt('TotalClosingCostsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Total Closing Costs(J)',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'TotalClosingCostsDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidLoanEstimate',
                'FormFieldHash' => bcrypt('ClosingCostsPaidLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Closing Costs Paid Before Closing',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsPaidLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidFinal',
                'FormFieldHash' => bcrypt('ClosingCostsPaidFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Closing Costs Paid Before Closing',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsPaidFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsPaidDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsPaidDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Closing Costs Paid Before Closing',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsPaidDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedLoanEstimate',
                'FormFieldHash' => bcrypt('ClosingCostsFinancedLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Closing Costs Financed (Paid fran your Loan Amount)',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsFinancedLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedFinal',
                'FormFieldHash' => bcrypt('ClosingCostsFinancedFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Closing Costs Financed (Paid fran your Loan Amount)',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsFinancedFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ClosingCostsFinancedDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsFinanced'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Closing Costs Financed (Paid fran your Loan Amount)',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsFinancedDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentLoanEstimate',
                'FormFieldHash' => bcrypt('DownPaymentLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Down Payment/Funds from Borrower',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DownPaymentLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentFinal',
                'FormFieldHash' => bcrypt('DownPaymentFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Down Payment/Funds from Borrower',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DownPaymentFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DownPaymentDidChange',
                'FormFieldHash' => bcrypt('ClosingCostsFinanced'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Down Payment/Funds from Borrower',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DownPaymentDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositLoanEstimate',
                'FormFieldHash' => bcrypt('DepositLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Deposit',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DepositLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositFinal',
                'FormFieldHash' => bcrypt('DepositFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Deposit',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DepositFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositDidChange',
                'FormFieldHash' => bcrypt('DepositDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Deposit',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'DepositDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsLoanEstimate',
                'FormFieldHash' => bcrypt('FundsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Funds for Borrower',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'FundsLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsFinal',
                'FormFieldHash' => bcrypt('FundsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Funds for Borrower',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'FundsFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'FundsDidChange',
                'FormFieldHash' => bcrypt('FundsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Funds for Borrower',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'FundsDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsLoanEstimate',
                'FormFieldHash' => bcrypt('SellerCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Seller Credits',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerCreditsLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsFinal',
                'FormFieldHash' => bcrypt('SellerCreditsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Seller Credits',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerCreditsFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditsDidChange',
                'FormFieldHash' => bcrypt('SellerCreditsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Seller Credits',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerCreditsDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsLoanEstimate',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Adjustment and Other Credits',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'AdjustmentAndOtherCreditsLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsFinal',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Adjustment and Other Credits',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'AdjustmentAndOtherCreditsFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AdjustmentAndOtherCreditsDidChange',
                'FormFieldHash' => bcrypt('AdjustmentAndOtherCreditsDidChange'),
                'InputTypeUID' => '3',
                'FormFieldLabel' => 'Adjustment and Other Credits',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'AdjustmentAndOtherCreditsDidChange',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'CashToCloseLoanEstimate',
                'FormFieldHash' => bcrypt('CashToCloseLoanEstimate'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Cash to Close',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CashToCloseLoanEstimate',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'CashToCloseFinal',
                'FormFieldHash' => bcrypt('CashToCloseFinal'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Cash to Close',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CashToCloseFinal',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Calculating Cash to Close',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerClosingDue',
                'FormFieldHash' => bcrypt('BorrowerClosingDue'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'K. Due from in Borrower at Closing',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'K. Due from in Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerClosingDue',
                'FormFieldHash' => bcrypt('SellerClosingDue'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'M.Due to Seller at Closing',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'General',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'M.Due to Seller at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerSalePrice',
                'FormFieldHash' => bcrypt('BorrowerSalePrice'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Sale Price of Property',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'BorrowerSalePrice',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'K. Due from in Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerSalePrice',
                'FormFieldHash' => bcrypt('SellerSalePrice'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Sale Price of Property',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'SellerSalePrice',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'M.Due to Seller at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerPersonalPropertySale',
                'FormFieldHash' => bcrypt('BorrowerPersonalPropertySale'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Sale Price of Any Personal I Property Included in Sale',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'PersonalPropertySale',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'K. Due from in Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerClosingCostPaidAtClosing',
                'FormFieldHash' => bcrypt('BorrowerClosingCostPaidAtClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Closing Costs Paid at Closing (J)',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'ClosingCostsPaid',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'K. Due from in Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerPersonalPropertySale',
                'FormFieldHash' => bcrypt('SellerPersonalPropertySale'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Sale Price of Any Personal I Property Included in Sale',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'PersonalPropertySale',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'M.Due to Seller at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'BorrowerAdjustments',
                'FormFieldHash' => bcrypt('BorrowerAdjustments'),
                'InputTypeUID' => '1',
                'FormFieldLabel' => 'Adjustments',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Adjustments',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'K. Due from in Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'CityAdjustmentsPaidbySellerinAdvance',
                'FormFieldHash' => bcrypt('CityAdjustmentsPaidbySellerinAdvance'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'City/Town Taxes to',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'City/Town Taxes to',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Adjustments for Items Paid by Seller in Advance',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'CityAdjustmentsPaidbySellerinAdvance',
                'FormFieldHash' => bcrypt('CityAdjustmentsPaidbySellerinAdvance'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'City/Town Taxes to',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'City/Town Taxes to',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Adjustments for Items Paid by Seller in Advance',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'CountyAdjustmentsPaidbySellerinAdvance',
                'FormFieldHash' => bcrypt('CountyAdjustmentsPaidbySellerinAdvance'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'CountyTaxes to',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'CountyTaxes to',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Adjustments for Items Paid by Seller in Advance',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'AssessmentstoAdjustmentsPaidbySellerinAdvance',
                'FormFieldHash' => bcrypt('AssessmentstoAdjustmentsPaidbySellerinAdvance'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Assessments to',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Assessments to',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Adjustments for Items Paid by Seller in Advance',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'HOADuesAdjustmentsPaidbySellerinAdvance',
                'FormFieldHash' => bcrypt('HOADuesAdjustmentsPaidbySellerinAdvance'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Assessments to',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Assessments to',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Adjustments for Items Paid by Seller in Advance',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'PaidAlreadybyorBehalfofBorroweratClosing',
                'FormFieldHash' => bcrypt('PaidAlreadybyorBehalfofBorroweratClosing'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'L. Paid Already by or on Behalf of Borrower at Closing',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'L. Paid Already by or on Behalf of Borrower at Closing',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'L. Paid Already by or on Behalf of Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'DepositPaidAlreadyby',
                'FormFieldHash' => bcrypt('DepositPaidAlreadyby'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Deposit',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Deposit',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'L. Paid Already by or on Behalf of Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'LoanAmountPaidAlreadyby',
                'FormFieldHash' => bcrypt('LoanAmountPaidAlreadyby'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'LoanAmount',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'LoanAmount',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'L. Paid Already by or on Behalf of Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'ExistingloanAssumedPaidAlreadyby',
                'FormFieldHash' => bcrypt('ExistingloanAssumedPaidAlreadyby'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Existing loan(s) Assumed or Taken Subject to',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Existing loan(s) Assumed or Taken Subject to',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'L. Paid Already by or on Behalf of Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'SellerCreditPaidAlreadyby',
                'FormFieldHash' => bcrypt('SellerCreditPaidAlreadyby'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Seller Credit',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Seller Credit',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'L. Paid Already by or on Behalf of Borrower at Closing',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'RebatefromEpsilonTitleCo.',
                'FormFieldHash' => bcrypt('RebatefromEpsilonTitleCo.'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Rebate from Epsilon Title Co.',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Rebate from Epsilon Title Co.',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Other Credit',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'RebatefromEpsilonTitleCo.',
                'FormFieldHash' => bcrypt('RebatefromEpsilonTitleCo.'),
                'InputTypeUID' => '5',
                'FormFieldLabel' => 'Rebate from Epsilon Title Co.',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Rebate from Epsilon Title Co.',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Other Credit',
                'Active' => 1,
            ],
            [
                'FormFieldName' =>'OtherCreditAdjustments',
                'FormFieldHash' => bcrypt('OtherCreditAdjustments'),
                'InputTypeUID' => '1',
                'FormFieldLabel' => 'Adjustments',
                'FormFieldLength'=> 100,    
                'FormFieldRequire' => 1,
                'FormFieldPosition' => '1',
                'FormFieldInstruction' => 'Adjustments',
                'FormFieldPlaceholder'=>'value',
                'FormGrouping'=>'Other Credit',
                'Active' => 1,
            ],

             
        ];
        DB::table('mFormFields')->insert($data);
    }
}
